### ISSUE TITLE
python-dnf is not installable with poetry

### ISSUE THREAD

**Issue by dcermak** [JaneSoo/rpm-dnf#1]
I am trying to use python-dnf with [poetry](https://python-poetry.org/), but sadly that is not possible:
```ShellSession
❯ cd $SOME_TEMP_DIR
❯ poetry init --name "test" --python "^3.9" --description "Just a test" --author "me" -n
❯ poetry add dnf
Creating virtualenv test-1TJxW-c5-py3.9 in /home/dan/.cache/pypoetry/virtualenvs
Using version ^0.0.2 for dnf

Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing dnf (0.0.2.1): Failed

  EnvCommandError

  Command ['/home/dan/.cache/pypoetry/virtualenvs/test-1TJxW-c5-py3.9/bin/pip', 'install', '--no-deps', 'file:///home/dan/.cache/pypoetry/artifacts/86/bf/66/de1d05c9c165e80b589d3454f956df095aea503f70c7a54ae0a1e7dc44/dnf-0.0.2.1.tar.gz'] errored with the following return code 1, and output:
  Processing /home/dan/.cache/pypoetry/artifacts/86/bf/66/de1d05c9c165e80b589d3454f956df095aea503f70c7a54ae0a1e7dc44/dnf-0.0.2.1.tar.gz
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /home/dan/.cache/pypoetry/virtualenvs/test-1TJxW-c5-py3.9/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ujsz9nr4/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ujsz9nr4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_5un7622
         cwd: /tmp/pip-req-build-ujsz9nr4/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-ujsz9nr4/setup.py", line 8, in <module>
        raise RuntimeError("Install aborted - please install python-dnf from distributiong system.")
    RuntimeError: Install aborted - please install python-dnf from distributiong system.
    ----------------------------------------
  WARNING: Discarding file:///home/dan/.cache/pypoetry/artifacts/86/bf/66/de1d05c9c165e80b589d3454f956df095aea503f70c7a54ae0a1e7dc44/dnf-0.0.2.1.tar.gz. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  WARNING: You are using pip version 21.3; however, version 21.3.1 is available.
  You should consider upgrading via the '/home/dan/.cache/pypoetry/virtualenvs/test-1TJxW-c5-py3.9/bin/python -m pip install --upgrade pip' command.


  at /usr/lib/python3.9/site-packages/poetry/utils/env.py:1075 in _run
      1071│                 output = subprocess.check_output(
      1072│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1073│                 )
      1074│         except CalledProcessError as e:
    → 1075│             raise EnvCommandError(e, input=input_)
      1076│
      1077│         return decode(output)
      1078│
      1079│     def execute(self, bin, *args, **kwargs):


Failed to add packages, reverting the pyproject.toml file to its original content.
```

My guess would be that this is caused by poetry using virtualenvs without system-site-packages set to true.

**Comment by brejoc** [comment]
Hey Dan, good to see you. Apologies for not outlining this more clear, but this failure is an expected behaviour. Currently there is no way of installing python-dnf from pypi. So this is just a dummy package. Up until now this dummy package was just printing a warning, but installed correctly. The poor souls that tried to use it had to figure out why they can't do an `import dnf`. So key here is this line: `RuntimeError: Install aborted - please install python-dnf from distributiong system.`

This way you simply can't install the dummy package and if - for whatever reason - this packages ends up in a CI run, the CI will fail closer to the origin of the problem.

**Comment by dcermak** [comment]
Hi Jochen! Fair enough, I mistakenly assumed that this package would satisfy the `dnf` or `rpm` dependency for poetry and just forward everything to `python-dnf` or `python-rpm`.

**Comment by brejoc** [comment]
One day that might be the case. But unfortunately that day isn't here yet! :sweat_smile:
